// Pandemonium Matrix data
const pandemoniumMatrix = {
    "0::0": { name: "LURGO (LEGBA)", description: "Amphidemon of Openings. (The Door of Doors)" },
    "1::0": { name: "DUODDOD", description: "Duplicitous Redoubler. Amphidemon of Abstract Addiction" },
    "2::0": { name: "PUPPO (THE PUP)", description: "Amphidemon of Larval Regression" },
    "2::1": { name: "DOOGU (THE BLOB)", description: "Cyclic Chronodemon of Splitting-Waters" },
    "3::0": { name: "IXIX (YIX)", description: "Chaotic Xenodemon of Cosmic Indifference" },
    "3::1": { name: "IXIGOOL (DJINN OF THE MAGI)", description: "Amphidemon of Tridentity (Sphinx-time)" },
    "3::2": { name: "IXIDOD (KING SID)", description: "Amphidemon of Escape-velocity" },
    "4::0": { name: "KRAKO (KRU, KARAK-OA)", description: "Amphidemon of Burning-Hail" },
    "4::1": { name: "SUKUGOOL (OLD SKUG)", description: "Cyclic Chronodemon of deluge and implosion" },
    "4::2": { name: "SKOODU (LI'L SCUD)", description: "Cyclic Chronodemon of Switch-Crazes" },
    "4::3": { name: "SKARKIX (SHARKY, SCAR-HEAD)", description: "Amphidemon of anti-evolution (eddies of the Delta)" },
    "5::0": { name: "TOKHATTO (OLD TOKER, TOP CAT)", description: "Amphidemon of Talismania" },
    "5::1": { name: "TUKKAMU", description: "Cyclic Chronodemon of Pathogenesis" },
    "5::2": { name: "KUTTADID (KITTY)", description: "Cyclic Chronodemon of Precarious States" },
    "5::3": { name: "TIKKITIX (TICKLER)", description: "Amphidemon of Vortical Delirium" },
    "5::4": { name: "KATAK", description: "Syzygetic Chronodemon of Cataclysmic Convergence" },
    "6::0": { name: "TCHU (TCHANUL)", description: "Chaotic Xenodemon of Ultimate Outsideness (and unnamable things)" },
    "6::1": { name: "DJUNGO", description: "Amphidemon of Subtle Involvements (and intricate puzzles)" },
    "6::2": { name: "DJUDDHA (JUDD DREAD)", description: "Amphidemon of Artificial Turbulence (complex-dynamics simulations)" },
    "6::3": { name: "DJYNXX (CHING, THE JINN)", description: "Syzygetic Xenodemon of Time-Lapse" },
    "6::4": { name: "TCHAKKI (CHUCKLES)", description: "Amphidemon of Combustion" },
    "6::5": { name: "TCHATTUK (ONE EYED JACK, DJATKA)", description: "Amphidemon of Unscreened Matrix" },
    "7::0": { name: "PUPPO (THE PUP)", description: "Amphidemon of Larval Regression" },
    "7::1": { name: "BUBBAMU (BUBS)", description: "Cyclic Chronodemon of Relapse" },
    "7::2": { name: "ODDUBB (ODBA)", description: "Syzygetic Chronodemon of Swamp-Labyrinths (and blind-doubles)" },
    "7::3": { name: "PABBAKIS (PABZIX)", description: "Amphidemon of Interference (and fakery)" },
    "7::4": { name: "ABABBATOK (ABRACADABRA)", description: "Cyclic Chronodemon of Suspended Decay" },
    "7::5": { name: "PAPATAKOO (PATAKU)", description: "Cyclic Chronodemon of Calendric Time" },
    "7::6": { name: "BOBOBJA (BUBBLES, BEELZEBUB)", description: "Amphidemon of Teeming Pestilence" },
    "8::0": { name: "MINOMMO", description: "Amphidemon of Submergance" },
    "8::1": { name: "MUR MUR (MURRUMUR, MU(MU))", description: "Syzygetic Chronodemon of the Deep Ones" },
    "8::2": { name: "NAMMAMAD", description: "Cyclic Chronodemon of Subterranean Commerce" },
    "8::3": { name: "MUMMUMIX (MIX-UP)", description: "Amphidemon of Insidious Fog (Nyarlathotep)" },
    "8::4": { name: "NUMKO (OLD NUK)", description: "Cyclic Chronodemon of Autochthony" },
    "8::5": { name: "MUNTUK (MANTA, MANITOU)", description: "Cyclic Chronodemon of Arid Seabeds" },
    "8::6": { name: "MOMMOLJO (MAMA JO)", description: "Amphidemon of Xenogenesis" },
    "8::7": { name: "MOMBBO", description: "Cyclic Chronodemon of Hybridity" },
    "9::0": { name: "UTTUNUL", description: "Syzygetic Xenodemon of Atonality" },
    "9::1": { name: "TUTAGOOL (YETTUK)", description: "Amphidemon of Punctuality" },
    "9::2": { name: "UNNUNDDO (THE FALSE NUN)", description: "Amphidemon of Endless Uncasing (onion-skin horror)" },
    "9::3": { name: "UNUNUTTIX (TICK-TOCK)", description: "Chaotic Xenodemon of Absolute Coincidence" },
    "9::4": { name: "UNUNAK (NUKE)", description: "Amphidemon of Convulsions" },
    "9::5": { name: "TUKUTU (KILLER-KATE)", description: "Amphidemon of Death-Strokes" },
    "9::6": { name: "UNNUTCHI (OUTCH, T'AI CHI)", description: "Chaotic Xenodemon of Coiling Outsideness" },
    "9::7": { name: "NUTTUBAB (NUT-CRACKER)", description: "Amphidemon of Metaloid Unlife" },
    "9::8": { name: "UMMNU (OM, OMNI, AMEN, OMEN)", description: "Amphidemon of Earth-Screams" }
};
